[workspace]
authors = ["gareth-cross <gcross.code@icloud.com>"]
channels = ["conda-forge"]
name = "qt-wgpu"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.0.3,<5"
ninja = ">=1.13.0,<2"
pre-commit = ">=4.2.0,<5"
